// <auto-generated />
using System;
using AppCenterApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppCenterApi.Data.Migrations
{
    [DbContext(typeof(ErrorsContext))]
    partial class ErrorsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppCenterApi.Data.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppBuild")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AppNamespace")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Locale")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Model")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OemName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OsBuild")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OsName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ScreenSize")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SdkName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SdkVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TimeZoneOffset")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Devices__3214EC07B8F1C2B7");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("AppCenterApi.Data.Entities.EventLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Sid")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__EventLog__3214EC074FAE5E2B");

                    b.HasIndex("DeviceId");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("AppCenterApi.Data.Entities.EventProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EventLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HandledErrorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PropertyValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__EventPro__3214EC07CA1148E6");

                    b.HasIndex("EventLogId");

                    b.HasIndex("HandledErrorId");

                    b.ToTable("EventProperties");
                });

            modelBuilder.Entity("AppCenterApi.Data.Entities.ExceptionDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("ParentExceptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Exceptio__3214EC07CB45A765");

                    b.HasIndex("ParentExceptionId");

                    b.ToTable("ExceptionDetails");
                });

            modelBuilder.Entity("AppCenterApi.Data.Entities.HandledErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExceptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sid")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__HandledE__3214EC07753C19D9");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ExceptionId");

                    b.ToTable("HandledErrorLogs");
                });

            modelBuilder.Entity("AppCenterApi.Data.Entities.ManagedErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AppLaunchTimestamp")
                        .HasColumnType("datetime");

                    b.Property<string>("Architecture")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExceptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Fatal")
                        .HasColumnType("bit");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<string>("ProcessName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Sid")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__ManagedE__3214EC077437F4FD");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ExceptionId");

                    b.ToTable("ManagedErrorLogs");
                });

            modelBuilder.Entity("AppCenterApi.Data.Entities.EventLog", b =>
                {
                    b.HasOne("AppCenterApi.Data.Entities.Device", "Device")
                        .WithMany("EventLogs")
                        .HasForeignKey("DeviceId")
                        .IsRequired()
                        .HasConstraintName("FK__EventLogs__Devic__2E1BDC42");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("AppCenterApi.Data.Entities.EventProperty", b =>
                {
                    b.HasOne("AppCenterApi.Data.Entities.EventLog", "EventLog")
                        .WithMany("EventProperties")
                        .HasForeignKey("EventLogId")
                        .HasConstraintName("FK_EventProperties_EventLogs");

                    b.HasOne("AppCenterApi.Data.Entities.HandledErrorLog", "HandledError")
                        .WithMany("EventProperties")
                        .HasForeignKey("HandledErrorId")
                        .HasConstraintName("FK_EventProperties_HandledErrorLogs");

                    b.Navigation("EventLog");

                    b.Navigation("HandledError");
                });

            modelBuilder.Entity("AppCenterApi.Data.Entities.ExceptionDetail", b =>
                {
                    b.HasOne("AppCenterApi.Data.Entities.ExceptionDetail", "ParentException")
                        .WithMany("InverseParentException")
                        .HasForeignKey("ParentExceptionId")
                        .HasConstraintName("FK__Exception__Paren__30F848ED");

                    b.Navigation("ParentException");
                });

            modelBuilder.Entity("AppCenterApi.Data.Entities.HandledErrorLog", b =>
                {
                    b.HasOne("AppCenterApi.Data.Entities.Device", "Device")
                        .WithMany("HandledErrorLogs")
                        .HasForeignKey("DeviceId")
                        .IsRequired()
                        .HasConstraintName("FK__HandledEr__Devic__31EC6D26");

                    b.HasOne("AppCenterApi.Data.Entities.ExceptionDetail", "Exception")
                        .WithMany("HandledErrorLogs")
                        .HasForeignKey("ExceptionId")
                        .IsRequired()
                        .HasConstraintName("FK__HandledEr__Excep__32E0915F");

                    b.Navigation("Device");

                    b.Navigation("Exception");
                });

            modelBuilder.Entity("AppCenterApi.Data.Entities.ManagedErrorLog", b =>
                {
                    b.HasOne("AppCenterApi.Data.Entities.Device", "Device")
                        .WithMany("ManagedErrorLogs")
                        .HasForeignKey("DeviceId")
                        .IsRequired()
                        .HasConstraintName("FK__ManagedEr__Devic__33D4B598");

                    b.HasOne("AppCenterApi.Data.Entities.ExceptionDetail", "Exception")
                        .WithMany("ManagedErrorLogs")
                        .HasForeignKey("ExceptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ManagedEr__Excep__34C8D9D1");

                    b.Navigation("Device");

                    b.Navigation("Exception");
                });

            modelBuilder.Entity("AppCenterApi.Data.Entities.Device", b =>
                {
                    b.Navigation("EventLogs");

                    b.Navigation("HandledErrorLogs");

                    b.Navigation("ManagedErrorLogs");
                });

            modelBuilder.Entity("AppCenterApi.Data.Entities.EventLog", b =>
                {
                    b.Navigation("EventProperties");
                });

            modelBuilder.Entity("AppCenterApi.Data.Entities.ExceptionDetail", b =>
                {
                    b.Navigation("HandledErrorLogs");

                    b.Navigation("InverseParentException");

                    b.Navigation("ManagedErrorLogs");
                });

            modelBuilder.Entity("AppCenterApi.Data.Entities.HandledErrorLog", b =>
                {
                    b.Navigation("EventProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
